"""
Per-squad Assault Fire / Spraying Fire capability, read from VASL counter art.

The same FP-Range-Morale string does NOT determine capability by itself (it
varies by nationality and squad class: the Russian SMG 6-2-8 has Assault
Fire, the NKVD 6-2-8 does not), but the rulebook defines the capability as a
property printed on the counter:

  A1.21 FIREPOWER (verified verbatim, eASLRB v3.14): "If the FP number is
    underlined, the unit may use the Assault FP bonus (7.36) during its AFPh."
  A7.36 ASSAULT FIRE (verified verbatim): "Assault Fire is restricted to
    squads armed primarily with SMG/semi-automatic rifles, as well as
    appropriate training in their use. Such squads are identified by the
    underscoring of their FP factor. Assault Fire capability allows any squad
    using its inherent FP during the AFPh to add one FP to its Small Arms
    Fire attack after all modification to the squad's inherent FP; any
    fraction in its FP is then rounded up. The Assault Fire bonus is not
    applicable to Opportunity Fire or Long Range Fire, but is still
    applicable to pinned-firers/Spraying-Fire in the AFPh."
  A7.34 SQUAD SPRAYING FIRE (verified verbatim): "Any squad with a Spraying
    Fire option is identified by the underscore beneath the Range portion of
    its Strength Factor. Squad Spraying Fire is identical to MG Spraying Fire
    (9.5) except that it is limited to a maximum range of three hexes."

VASL 6.7.3 draws those underscores as explicit, machine-readable SVG
elements: every squad counter SVG (images/<nat>/<nat><FP><Range><Morale>
<class><variant>.svg) contains
    <line id="AssaultFire" .../>   for the underscored FP factor, and/or
    <line id="SprayingFire" .../>  for the underscored Range factor.
ART_CAPABILITIES below was generated by scanning every squad/HS/crew SVG of
the 8 covered nationalities in ~/vasl/vasl-6.7.3.vmod for those element ids
(165 counters; art lacking a printed Strength Factor — broken sides, blank
placeholders — was skipped). Spot checks against the eASLRB text all agree:

  * A7.31 EX gives the American 6-6-6 and German 5-4-8 the Assault Fire +1
    (art: am666S/ge548S have AssaultFire).
  * The A25.11 SS designer note: the morale factor "of Late War SS MMC
    [EXC: SS 8-3-8s/3-3-8s] is never considered underscored" and "SS 6-5-8
    squads are entitled to Assault Fire capabilities in any scenario during
    1944-45" — i.e. the 6-5-8 counter itself is NOT underscored (art agrees:
    ge658Ss has no AssaultFire element); the 1944-45 grant is a conditional
    NOT printed on the counter, surfaced via CONDITIONAL_NOTES.
  * The A25 Russian NKVD designer note: "its combat deficiencies are
    reflected by its 2nd-Line status and the lack of Assault Fire capability
    normally associated with SMG-armed squads" (art agrees: ru628SN has
    SprayingFire only, vs the regular SMG ru628S which has both).
  * A25.53: "in/after 12/43, Free French squads have Assault Fire (7.36)
    capability" — conditional, not printed on French counters (art agrees:
    no French squad has an underscore); surfaced via CONDITIONAL_NOTES.

One art oddity found (reported, kept as scanned): the SS conscript 4-3-6
(ge436Ss) lacks the SprayingFire element while the regular German 4-3-6
(ge436S) has it. Encoded as scanned — the counter art is the rule's own
definition of the capability (A1.21/A7.34) — but flagged in the entry note.

Nationalities NOT covered (Axis Minor, Allied Minor, Chinese, Partisan, ...)
fall through to (None, None) = "unknown": callers must warn instead of
applying a capability. Note A25.9: "Polish and Belgian elite and 1st Line
squads should generally be assigned Assault Fire (7.36) via a SSR."
"""
import re
from typing import Any, Dict, Optional, Tuple

# (assault_fire, spraying_fire) keyed by counter-art stem (file name without
# directory/extension), e.g. parse_vsav's unit["art"] "fi/fi648S.svg" ->
# "fi648S". Generated from VASL 6.7.3 SVG underscore elements (see module
# docstring); the trailing comment is the counter's printed FP-Range-Morale.
ART_CAPABILITIES: Dict[str, Tuple[bool, bool]] = {
    "am126C": (False, False),    # 1-2-6
    "am126H": (False, False),    # 1-2-6
    "am226H": (False, False),    # 2-2-6
    "am227C": (False, False),    # 2-2-7
    "am227CSF": (False, False),  # 2-2-7
    "am228C": (False, False),    # 2-2-8
    "am228CSF": (False, False),  # 2-2-8
    "am236H": (False, False),    # 2-3-6
    "am237H": (False, False),    # 2-3-7
    "am238H": (False, False),    # 2-3-8
    "am248H": (False, False),    # 2-4-8
    "am336S": (False, False),    # 3-3-6
    "am337H": (False, False),    # 3-3-7
    "am337Hae": (False, False),  # 3-3-7
    "am346H": (False, False),    # 3-4-6
    "am347H": (False, False),    # 3-4-7
    "am348H": (False, False),    # 3-4-8
    "am348Hae": (False, False),  # 3-4-8
    "am447S": (False, False),    # 4-4-7
    "am458S": (False, False),    # 4-5-8
    "am536S": (True, False),     # 5-3-6
    "am546S": (True, False),     # 5-4-6
    "am558S": (False, True),     # 5-5-8
    "am666S": (True, False),     # 6-6-6
    "am667S": (True, False),     # 6-6-7
    "am668S": (True, False),     # 6-6-8
    "am747S": (True, True),      # 7-4-7
    "am747Sae": (True, True),    # 7-4-7
    "am768S": (True, True),      # 7-6-8
    "am768Sae": (True, True),    # 7-6-8
    "br127C": (False, False),    # 1-2-7
    "br226H": (False, False),    # 2-2-6
    "br228C": (False, False),    # 2-2-8
    "br237H": (False, False),    # 2-3-7
    "br247H": (False, False),    # 2-4-7
    "br248H": (False, False),    # 2-4-8
    "br338H": (False, False),    # 3-3-8
    "br338Hae": (False, False),  # 3-3-8
    "br436S": (False, False),    # 4-3-6
    "br447S": (False, False),    # 4-4-7
    "br457S": (False, False),    # 4-5-7
    "br458S": (False, False),    # 4-5-8
    "br648S": (True, True),      # 6-4-8
    "br648Sae": (True, True),    # 6-4-8
    "fi127C": (False, False),    # 1-2-7
    "fi228C": (False, False),    # 2-2-8
    "fi238H": (False, False),    # 2-3-8
    "fi248H": (False, False),    # 2-4-8
    "fi338H": (False, False),    # 3-3-8
    "fi338Hae": (False, False),  # 3-3-8
    "fi538S": (True, True),      # 5-3-8
    "fi648S": (True, True),      # 6-4-8
    "fi838S": (True, True),      # 8-3-8
    "fi838Sae": (True, True),    # 8-3-8
    "fr127C": (False, False),    # 1-2-7
    "fr227H": (False, False),    # 2-2-7
    "fr228C": (False, False),    # 2-2-8
    "fr237H": (False, False),    # 2-3-7
    "fr248H": (False, False),    # 2-4-8
    "fr248Hae": (False, False),  # 2-4-8
    "fr437S": (False, False),    # 4-3-7
    "fr457S": (False, False),    # 4-5-7
    "fr458S": (False, False),    # 4-5-8
    "fr458Sae": (False, False),  # 4-5-8
    "ge127C": (False, False),    # 1-2-7
    "ge128C": (False, False),    # 1-2-8
    "ge128H": (False, False),    # 1-2-8
    "ge228C": (False, False),    # 2-2-8
    "ge228Cp": (False, False),   # 2-2-8
    "ge228S": (False, False),    # 2-2-8
    "ge236H": (False, False),    # 2-3-6
    "ge236Hs": (False, False),   # 2-3-6
    "ge237H": (False, False),    # 2-3-7
    "ge237H_sap": (False, False),    # 2-3-7
    "ge237Hs": (False, False),   # 2-3-7
    "ge238H": (False, False),    # 2-3-8
    "ge238Hae": (False, False),  # 2-3-8
    "ge238Hae_sap": (False, False),  # 2-3-8
    "ge238Hp": (False, False),   # 2-3-8
    "ge238Hs": (False, False),   # 2-3-8
    "ge238Hsae": (False, False),     # 2-3-8
    "ge247H": (False, False),    # 2-4-7
    "ge248H": (False, False),    # 2-4-8
    "ge248Hae": (False, False),  # 2-4-8
    "ge248Hs": (False, False),   # 2-4-8
    "ge338H": (False, False),    # 3-3-8
    "ge338Hae": (False, False),  # 3-3-8
    "ge338Hs": (False, False),   # 3-3-8
    "ge338Hsae": (False, False),     # 3-3-8
    "ge348Hs": (False, False),   # 3-4-8
    "ge436S": (False, True),     # 4-3-6
    "ge436Ss": (False, False),   # 4-3-6 SS — art has no SprayingFire (oddity, see docstring)
    "ge447S": (False, True),     # 4-4-7
    "ge447S_sap": (False, False),    # 4-4-7 (variant art lacks SprayingFire)
    "ge447Ss": (False, True),    # 4-4-7
    "ge467S": (False, True),     # 4-6-7
    "ge468S": (False, True),     # 4-6-8
    "ge468Sae": (False, True),   # 4-6-8
    "ge468Ss": (False, True),    # 4-6-8
    "ge537S": (True, True),      # 5-3-7
    "ge548S": (True, True),      # 5-4-8
    "ge548Sae": (True, True),    # 5-4-8
    "ge548Sae_sap": (True, True),    # 5-4-8
    "ge548Sp": (True, True),     # 5-4-8
    "ge548Ss": (True, True),     # 5-4-8
    "ge548Ssae": (True, True),   # 5-4-8
    "ge658Ss": (False, True),    # 6-5-8 SS — AF 1944-45 only via A25.11 (CONDITIONAL_NOTES)
    "ge838S": (True, True),      # 8-3-8
    "ge838Sae": (True, True),    # 8-3-8
    "ge838Ss": (True, True),     # 8-3-8
    "ge838Ssae": (True, True),   # 8-3-8
    "it126C": (False, False),    # 1-2-6
    "it126H": (False, False),    # 1-2-6
    "it136H": (False, False),    # 1-3-6
    "it137H": (False, False),    # 1-3-7
    "it227C": (False, False),    # 2-2-7
    "it247H": (False, False),    # 2-4-7
    "it247Hae": (False, False),  # 2-4-7
    "it336S": (False, False),    # 3-3-6
    "it346S": (False, False),    # 3-4-6
    "it347S": (False, False),    # 3-4-7
    "it447S": (False, False),    # 4-4-7
    "it447Sae": (False, False),  # 4-4-7
    "ja126H": (False, False),    # 1-2-6
    "ja126Hk": (False, False),   # 1-2-6
    "ja127C": (False, False),    # 1-2-7
    "ja128Cr": (False, False),   # 1-2-8
    "ja137H": (False, False),    # 1-3-7
    "ja226Sr": (False, False),   # 2-2-6
    "ja228C": (False, False),    # 2-2-8
    "ja237H": (False, False),    # 2-3-7
    "ja237Sr": (False, False),   # 2-3-7
    "ja238H": (False, False),    # 2-3-8
    "ja238Hae": (False, False),  # 2-3-8
    "ja336S": (False, False),    # 3-3-6
    "ja336Sk": (False, False),   # 3-3-6
    "ja347S": (False, False),    # 3-4-7
    "ja347Sr": (False, False),   # 3-4-7
    "ja348Sr": (False, False),   # 3-4-8
    "ja348Srae": (False, False),     # 3-4-8
    "ja447S": (False, False),    # 4-4-7
    "ja448S": (False, False),    # 4-4-8
    "ja448Sae": (False, False),  # 4-4-8
    "ru127C": (False, False),    # 1-2-7
    "ru226H": (False, False),    # 2-2-6
    "ru227H": (False, False),    # 2-2-7
    "ru228C": (False, False),    # 2-2-8
    "ru237H": (False, False),    # 2-3-7
    "ru248H": (False, False),    # 2-4-8
    "ru248HN": (False, False),   # 2-4-8
    "ru248H_para": (False, False),   # 2-4-8
    "ru328H": (False, False),    # 3-2-8
    "ru328HN": (False, False),   # 3-2-8
    "ru328Hae": (False, False),  # 3-2-8
    "ru328Hae_sap": (False, False),  # 3-2-8
    "ru426S": (False, False),    # 4-2-6
    "ru447S": (False, False),    # 4-4-7
    "ru458S": (False, False),    # 4-5-8
    "ru458SN": (False, False),   # 4-5-8
    "ru458S_para": (False, False),   # 4-5-8
    "ru527S": (True, True),      # 5-2-7
    "ru628S": (True, True),      # 6-2-8
    "ru628SN": (False, True),    # 6-2-8 NKVD — no AF (A25 Russian designer note agrees)
    "ru628Sae": (True, True),    # 6-2-8
    "ru628Sae_sap": (True, True),    # 6-2-8
}

# Conditional capabilities granted by rule/SSR, NOT printed on the counter —
# surfaced as notes, never auto-applied.
CONDITIONAL_NOTES: Dict[str, str] = {
    "ge658Ss": ("SS 6-5-8: entitled to Assault Fire in any 1944-45 scenario "
                "(A25.11 note) — not printed on the counter, NOT auto-applied"),
}
_FREE_FRENCH_NOTE = ("French squad: Free French squads have Assault Fire "
                     "in/after 12/43 (A25.53) — not printed on the counter, "
                     "NOT auto-applied")

# Side name (as parse_vsav emits it) -> VASL art prefix, for the name-based
# fallback key. Only the 8 scanned nationalities.
_SIDE_PREFIX = {"German": "ge", "Russian": "ru", "American": "am",
                "British": "br", "Finnish": "fi", "Italian": "it",
                "Japanese": "ja", "French": "fr"}

_STEM_RE = re.compile(r"^(ge|ru|am|br|fi|it|ja|fr)(\d)(\d)(\d)(S|H|C)")
# "6-4-8 1sq" / "4-5-8 Esq" / "2-2-8 Icr" / "3-4-8 2hs" -> strength + class.
_NAME_RE = re.compile(r"^(\d+(?:\.5)?-\d+-\d+)\b.*?(sq|hs|cr)\s*$",
                      re.IGNORECASE)
_CLASS_LETTER = {"sq": "S", "hs": "H", "cr": "C"}


def _build_name_fallback() -> Dict[Tuple[str, str, str], Tuple[Optional[bool], Optional[bool]]]:
    """(art prefix, 'FP-Range-Morale', class letter) -> capabilities.

    Aggregated over all art variants of the same printed strength/class
    (Sae, Ss, SN, _para, ...): a capability is only asserted when EVERY
    variant agrees; otherwise None ("ambiguous — depends on the exact
    counter", e.g. Russian 6-2-8 SMG vs NKVD for Assault Fire). "_sap"
    alternate-art variants are excluded from aggregation (one of them,
    ge447S_sap, drops an underscore its base art has).
    """
    agg: Dict[Tuple[str, str, str], list] = {}
    for stem, caps in ART_CAPABILITIES.items():
        if "_sap" in stem:
            continue
        m = _STEM_RE.match(stem)
        if not m:
            continue
        key = (m.group(1), f"{m.group(2)}-{m.group(3)}-{m.group(4)}",
               m.group(5))
        agg.setdefault(key, []).append(caps)
    out = {}
    for key, values in agg.items():
        af_vals = {v[0] for v in values}
        sf_vals = {v[1] for v in values}
        out[key] = (af_vals.pop() if len(af_vals) == 1 else None,
                    sf_vals.pop() if len(sf_vals) == 1 else None)
    return out


NAME_FALLBACK = _build_name_fallback()


def art_stem(art: Optional[str]) -> Optional[str]:
    """'fi/fi648S.svg' (or 'fi648S.gif', or a full VASL path) -> 'fi648S'."""
    if not art:
        return None
    base = art.replace("\\", "/").rsplit("/", 1)[-1]
    return base.rsplit(".", 1)[0] or None


def lookup(art: Optional[str] = None, side: Optional[str] = None,
           name: Optional[str] = None) -> Dict[str, Any]:
    """Capability lookup for one personnel counter.

    Returns {"assault_fire": True/False/None, "spraying_fire": ditto,
    "source": str|None, "note": str|None}. None = unknown — the caller must
    warn rather than apply. Primary key: exact counter-art stem; fallback:
    (nationality, FP-Range-Morale string, squad/HS/crew class from the VASL
    piece name), which is only asserted where unambiguous across counters.
    """
    out: Dict[str, Any] = {"assault_fire": None, "spraying_fire": None,
                           "source": None, "note": None}
    stem = art_stem(art)
    if stem and stem in ART_CAPABILITIES:
        af, sf = ART_CAPABILITIES[stem]
        out.update(assault_fire=af, spraying_fire=sf,
                   source=f"counter art {stem} (VASL 6.7.3 underscore elements)")
        out["note"] = CONDITIONAL_NOTES.get(stem) or (
            _FREE_FRENCH_NOTE if stem.startswith("fr") and stem[5:6] == "S"
            else None)
        return out
    prefix = _SIDE_PREFIX.get(side or "")
    m = _NAME_RE.match((name or "").strip())
    if prefix and m:
        key = (prefix, m.group(1), _CLASS_LETTER[m.group(2).lower()])
        if key in NAME_FALLBACK:
            af, sf = NAME_FALLBACK[key]
            out.update(
                assault_fire=af, spraying_fire=sf,
                source=f"nationality + printed strength fallback "
                       f"({side} {m.group(1)} {m.group(2).lower()})")
            if af is None or sf is None:
                out["note"] = ("capability ambiguous for this strength/class "
                               "across counter variants — exact counter art "
                               "needed")
            if prefix == "fr" and key[2] == "S":
                out["note"] = _FREE_FRENCH_NOTE
            return out
    return out
