#!/usr/bin/env python
"""
Tests for app/asl/unit_capabilities.py — deterministic Assault Fire (A7.36)
/ Spraying Fire (A7.34) capability detection from VASL counter art.

The table was generated by scanning every squad/HS/crew SVG in VASL 6.7.3
for the explicit underscore elements (<line id="AssaultFire">, <line
id="SprayingFire">) that render the rulebook's capability markings (A1.21:
"If the FP number is underlined, the unit may use the Assault FP bonus
(7.36)"; A7.34: underscore beneath the Range portion).

Runnable directly (`python tests/test_unit_capabilities.py`) or under
pytest. No network, no DB.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.asl import unit_capabilities as uc


# --------------------------------------------------------------------------- #
# (1) Exact counter-art lookups across nationalities
# --------------------------------------------------------------------------- #

def test_art_lookup_known_counters_eight_nationalities():
    # (art path, expected assault fire, expected spraying fire)
    cases = [
        ("fi/fi648S.svg", True, True),    # Finnish 1st line 6-4-8
        ("fi/fi838S.svg", True, True),    # Finnish elite 8-3-8
        ("ge/ge467S.svg", False, True),   # German 1st line 4-6-7
        ("ge/ge548S.svg", True, True),    # German SMG 5-4-8 (A7.31 EX agrees)
        ("ge/ge838S.svg", True, True),    # German assault engineer 8-3-8
        ("am/am666S.svg", True, False),   # American 1st line 6-6-6 (A7.31 EX)
        ("am/am747S.svg", True, True),    # USMC 7-4-7
        ("ru/ru447S.svg", False, False),  # Russian 1st line 4-4-7
        ("ru/ru628S.svg", True, True),    # Russian SMG 6-2-8
        ("br/br648S.svg", True, True),    # British Gurkha/elite 6-4-8
        ("br/br458S.svg", False, False),  # British elite 4-5-8
        ("it/it447S.svg", False, False),  # Italian elite 4-4-7
        ("ja/ja448S.svg", False, False),  # Japanese elite 4-4-8
        ("fr/fr458S.svg", False, False),  # French elite 4-5-8
    ]
    for art, af, sf in cases:
        got = uc.lookup(art=art)
        assert got["assault_fire"] is af and got["spraying_fire"] is sf, \
            (art, got)
        assert got["source"] and "counter art" in got["source"], got


def test_same_strength_string_differs_by_counter():
    """The FP-range-morale string alone does NOT determine capability:
    Russian SMG 6-2-8 has Assault Fire, the NKVD 6-2-8 does not (per the
    A25 Russian designer note and the counter art)."""
    smg = uc.lookup(art="ru/ru628S.svg")
    nkvd = uc.lookup(art="ru/ru628SN.svg")
    assert smg["assault_fire"] is True and nkvd["assault_fire"] is False
    assert smg["spraying_fire"] is True and nkvd["spraying_fire"] is True


def test_half_squads_and_crews_have_no_capability():
    # A7.36: "restricted to squads" — no HS/crew counter is underscored.
    for art in ("fi/fi248H.svg", "ge/ge238H.svg", "am/am348H.svg",
                "ru/ru228C.svg", "ja/ja228C.svg"):
        got = uc.lookup(art=art)
        assert got["assault_fire"] is False and got["spraying_fire"] is False, \
            (art, got)


def test_conditional_capability_notes():
    # SS 6-5-8: Assault Fire only in 1944-45 via A25.11 — note, not applied.
    ss = uc.lookup(art="ge/ge658Ss.svg")
    assert ss["assault_fire"] is False, ss
    assert ss["note"] and "A25.11" in ss["note"] and "1944-45" in ss["note"], ss
    # Free French squads: Assault Fire in/after 12/43 via A25.53 — note only.
    fr = uc.lookup(art="fr/fr458S.svg")
    assert fr["assault_fire"] is False, fr
    assert fr["note"] and "A25.53" in fr["note"], fr
    # But French crews/HS get no such note.
    assert uc.lookup(art="fr/fr127C.svg")["note"] is None


# --------------------------------------------------------------------------- #
# (2) Name fallback (nationality + printed strength + class)
# --------------------------------------------------------------------------- #

def test_name_fallback_when_art_missing():
    got = uc.lookup(side="American", name="6-6-6 1sq")
    assert got["assault_fire"] is True and got["spraying_fire"] is False, got
    assert got["source"] and "fallback" in got["source"], got
    got = uc.lookup(side="German", name="4-6-7 1sq")
    assert got["assault_fire"] is False and got["spraying_fire"] is True, got
    got = uc.lookup(side="Finnish", name="6-4-8 1sq")
    assert got["assault_fire"] is True and got["spraying_fire"] is True, got
    # Class matters: the Finnish 2-4-8 half-squad has neither.
    got = uc.lookup(side="Finnish", name="2-4-8 1hs")
    assert got["assault_fire"] is False and got["spraying_fire"] is False, got


def test_name_fallback_ambiguous_returns_none():
    """Russian '6-2-8' squads split between SMG (Assault Fire) and NKVD
    (no Assault Fire): the name fallback must refuse to guess."""
    got = uc.lookup(side="Russian", name="6-2-8 Esq")
    assert got["assault_fire"] is None, got
    assert got["spraying_fire"] is True, got    # all 6-2-8 variants agree
    assert got["note"] and "ambiguous" in got["note"], got


def test_exact_art_beats_name_fallback():
    got = uc.lookup(art="ru/ru628SN.svg", side="Russian", name="6-2-8 2sq")
    assert got["assault_fire"] is False, got    # NKVD, not ambiguous


# --------------------------------------------------------------------------- #
# (3) Unknown counters stay unknown
# --------------------------------------------------------------------------- #

def test_unknown_unit_returns_none():
    for kw in (dict(side="Chinese", name="4-4-7 1sq"),       # nat not covered
               dict(side="AxisMinor", name="4-4-7 1sq"),
               dict(art="ch/ch447S.svg"),                     # art not in table
               dict(side="German", name="9-9-9 1sq"),         # no such counter
               dict()):
        got = uc.lookup(**kw)
        assert got["assault_fire"] is None and got["spraying_fire"] is None, \
            (kw, got)
        assert got["source"] is None, (kw, got)


def test_art_stem_normalization():
    assert uc.art_stem("fi/fi648S.svg") == "fi648S"
    assert uc.art_stem("ru/ru447S.gif") == "ru447S"
    assert uc.art_stem("fi648S.svg") == "fi648S"
    assert uc.art_stem(None) is None
    assert uc.art_stem("") is None


# --------------------------------------------------------------------------- #
# Runner
# --------------------------------------------------------------------------- #

if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items())
             if k.startswith("test_") and callable(v)]
    failures = 0
    for t in tests:
        try:
            t()
            print(f"  ✅ {t.__name__}")
        except Exception as e:
            failures += 1
            print(f"  ❌ {t.__name__}: {e}")
    print(f"\n{len(tests) - failures}/{len(tests)} passed")
    sys.exit(1 if failures else 0)
